INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(40, 'Caterpie', 'Its short feet are tipped with suction pads.', 'String Shot', '10', 'Fire', NULL, '1 Colorless', 45, 1, 3, 1),
(60, 'Metapod', 'Hardens its shell to protect itself.', 'Harden', '—', 'Fire', NULL, '2 Colorless', 54, 1, 3, 2),
(80, 'Butterfree', 'In battle, it flaps its wings at high speed.', 'Whirlwind', '20', 'Fire', NULL, '1 Colorless', 3, 1, 3, 3),
(50, 'Weedle', 'Often found in forests, eating leaves.', 'Poison Sting', '10', 'Fire', NULL, '1 Colorless', 69, 1, 3, 1),
(70, 'Kakuna', 'Almost incapable of moving.', 'Stiffen', '—', 'Fire', NULL, '2 Colorless', 33, 1, 3, 2),
(80, 'Beedrill', 'Flies at high speed and attacks using its large stingers.', 'Twineedle', '30x', 'Fire', NULL, '2 Colorless', 17, 1, 3, 3),
(60, 'Oddish', 'During the day, it stays in the ground.', 'Absorb', '20', 'Fire', NULL, '1 Colorless', 58, 2, 3, 1),
(70, 'Gloom', 'Smells incredibly foul.', 'Poisonpowder', '30', 'Fire', NULL, '2 Colorless', 32, 2, 3, 2),
(90, 'Vileplume', 'Its petals are the largest in the world.', 'Petal Dance', '40x', 'Fire', NULL, '2 Colorless', 15, 2, 3, 3),
(50, 'Meowth', 'Adores circular objects.', 'Pay Day', '10', 'Fighting', NULL, '1 Colorless', 56, 2, 7, 1),
(70, 'Persian', 'Although its fur is beautiful, it is tough to raise.', 'Scratch', '20', 'Fighting', NULL, '1 Colorless', 42, 2, 7, 2),
(90, 'Kangaskhan', 'Raises its young in its belly pouch.', 'Comet Punch', '20x', 'Fighting', NULL, '3 Colorless', 5, 2, 7, 1),
(60, 'Cubone', 'Wears the skull of its deceased mother.', 'Bone Club', '20', 'Grass', NULL, '1 Colorless', 50, 2, 6, 1),
(80, 'Marowak', 'The bone it holds is its weapon.', 'Bonemerang', '30x', 'Grass', NULL, '2 Colorless', 39, 2, 6, 2),
(100, 'Hitmonlee', 'Extends its legs at will.', 'Stretch Kick', '—', 'Psychic', NULL, '1 Colorless', 7, 2, 6, 1),
(100, 'Hitmonchan', 'Punches with an icy fist.', 'Special Punch', '40', 'Psychic', NULL, '2 Colorless', 7, 1, 6, 1),
(70, 'Machop', 'Loves to build its muscles.', 'Low Kick', '20', 'Psychic', NULL, '1 Colorless', 52, 1, 6, 1),
(80, 'Machoke', 'Its muscles are very strong.', 'Karate Chop', '50', 'Psychic', NULL, '2 Colorless', 34, 1, 6, 2),
(100, 'Machamp', 'Using its four arms, it can attack in all directions.', 'Seismic Toss', '60', 'Psychic', NULL, '3 Colorless', 8, 1, 6, 3),
(60, 'Abra', 'Sleeps 18 hours a day.', 'Psyshock', '10', 'Psychic', NULL, '1 Colorless', 43, 1, 5, 1),
(70, 'Kadabra', 'Its brain can outperform a supercomputer.', 'Recover', '—', 'Psychic', NULL, '2 Colorless', 32, 1, 5, 2),
(100, 'Alakazam', 'Its brain continually grows.', 'Confuse Ray', '30', 'Psychic', NULL, '3 Colorless', 1, 1, 5, 3),
(60, 'Drowzee', 'Puts enemies to sleep.', 'Pound', '10', 'Psychic', NULL, '1 Colorless', 49, 1, 5, 1),
(80, 'Hypno', 'Carries a pendulum to hypnotize.', 'Meditate', '10+', 'Psychic', NULL, '2 Colorless', 8, 2, 5, 2),
(90, 'Mewtwo', 'Genetic Pokémon created by science.', 'Psychic', '40+', 'Psychic', NULL, '3 Colorless', 10, 1, 5, 1),
(100, 'Mew', 'So rare that it is said to be a mirage.', 'Pound', '10', 'Psychic', NULL, '1 Colorless', 151, 1, 5, 1),
(70, 'Magnemite', 'Uses anti-gravity to stay suspended.', 'Thunder Wave', '10', 'Fighting', 'Steel', '1 Colorless', 62, 1, 4, 1),
(80, 'Magneton', 'Formed by several Magnemite.', 'Selfdestruct', '80', 'Fighting', 'Steel', '2 Colorless', 9, 1, 4, 2),
(60, 'Voltorb', 'Usually found in power plants.', 'Tackle', '10', 'Fighting', NULL, '1 Colorless', 67, 1, 4, 1),
(80, 'Electrode', 'Stores electrical energy inside its body.', 'Explosion', '80', 'Fighting', NULL, '2 Colorless', 21, 1, 4, 2);
