INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(40, 'Pidgey', 'A common sight in forests and woods.', 'Gust', '10', 'Electric', NULL, '1 Colorless', 57, 1, 7, 1),
(60, 'Pidgeotto', 'Very protective of its territory.', 'Whirlwind', '20', 'Electric', NULL, '1 Colorless', 22, 1, 7, 2),
(80, 'Pidgeot', 'When hunting, it skims the surface of water.', 'Wing Attack', '30', 'Electric', NULL, '2 Colorless', 8, 1, 7, 3),
(50, 'Rattata', 'Bites anything when it attacks.', 'Bite', '20', 'Fighting', NULL, '1 Colorless', 61, 1, 7, 1),
(70, 'Raticate', 'Gnaws on anything with its tough fangs.', 'Super Fang', '—', 'Fighting', NULL, '1 Colorless', 40, 1, 7, 2),
(60, 'Spearow', 'Eats bugs in grassy areas.', 'Peck', '10', 'Electric', NULL, '1 Colorless', 62, 1, 7, 1),
(80, 'Fearow', 'With its huge and magnificent wings.', 'Agility', '20', 'Electric', NULL, '1 Colorless', 36, 1, 7, 2),
(50, 'Ekans', 'Moves silently and stealthily.', 'Wrap', '10', 'Psychic', NULL, '1 Colorless', 56, 1, 6, 1),
(80, 'Arbok', 'It is rumored to be able to crush opponents.', 'Poison Fang', '20', 'Psychic', NULL, '2 Colorless', 2, 1, 6, 2),
(60, 'Sandshrew', 'Burrows deep underground.', 'Scratch', '20', 'Water', NULL, '1 Colorless', 64, 1, 6, 1),
(80, 'Sandslash', 'Curls up into a spiny ball.', 'Slash', '30', 'Water', NULL, '1 Colorless', 31, 1, 6, 2),
(70, 'Nidoran♀', 'Small but fierce.', 'Scratch', '20', 'Psychic', NULL, '1 Colorless', 32, 2, 3, 1),
(80, 'Nidorina', 'The female evolves quickly.', 'Double Kick', '30x', 'Psychic', NULL, '2 Colorless', 36, 2, 3, 2),
(100, 'Nidoqueen', 'Its body is covered with hard scales.', 'Mega Punch', '40', 'Psychic', NULL, '3 Colorless', 7, 2, 3, 3),
(70, 'Nidoran♂', 'Its horn is filled with poison.', 'Horn Attack', '20', 'Psychic', NULL, '1 Colorless', 33, 2, 6, 1),
(80, 'Nidorino', 'Quick to anger.', 'Horn Drill', '50', 'Psychic', NULL, '2 Colorless', 37, 2, 6, 2),
(100, 'Nidoking', 'Its tail is thick and powerful.', 'Thrash', '30+', 'Psychic', NULL, '3 Colorless', 11, 2, 6, 3),
(60, 'Zubat', 'Forms colonies in dark places.', 'Leech Life', '10', 'Psychic', NULL, '1 Colorless', 57, 3, 6, 1),
(80, 'Golbat', 'Attacks in a swarm.', 'Wing Attack', '30', 'Psychic', NULL, '2 Colorless', 25, 3, 6, 2),
(90, 'Paras', 'Burrows to plant mushrooms.', 'Scratch', '20', 'Fire', NULL, '1 Colorless', 60, 2, 3, 1),
(100, 'Parasect', 'The bug is controlled by the mushroom.', 'Spore', '—', 'Fire', NULL, '2 Colorless', 34, 2, 3, 2),
(70, 'Venonat', 'Lives in the shadows of tall trees.', 'Stun Spore', '10', 'Fire', NULL, '1 Colorless', 63, 2, 3, 1),
(90, 'Venomoth', 'Scatters powder to paralyze opponents.', 'Venom Powder', '10', 'Fire', NULL, '1 Colorless', 13, 2, 3, 2),
(60, 'Diglett', 'Lives about one yard underground.', 'Dig', '10', 'Grass', NULL, '1 Colorless', 47, 1, 6, 1),
(80, 'Dugtrio', 'Burrows deep underground.', 'Earthquake', '70', 'Grass', NULL, '2 Colorless', 19, 1, 6, 2),
(70, 'Geodude', 'Found in fields and mountains.', 'Tackle', '20', 'Grass', NULL, '1 Colorless', 36, 3, 6, 1),
(90, 'Graveler', 'Rolls down slopes.', 'Rock Throw', '40', 'Grass', NULL, '2 Colorless', 37, 3, 6, 2),
(110, 'Golem', 'Its body is rock hard.', 'Explosion', '100', 'Grass', NULL, '3 Colorless', 26, 3, 6, 3),
(60, 'Onix', 'Burrows at high speed.', 'Rock Throw', '10', 'Grass', NULL, '1 Colorless', 56, 1, 6, 1),
(100, 'Rhydon', 'Its horn can crush diamonds.', 'Horn Drill', '50', 'Grass', NULL, '3 Colorless', 45, 2, 6, 2);
